[package]
name = "simplehddserial"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = "1.5.0"
lazy_static = "1.5.0"
winapi = { version = "0.3.9", features = ["winuser", "fileapi", "winerror", "winioctl", "ioapiset", "handleapi"] }
